# Generated by Django 2.0.2 on 2018-02-14 06:18

import Events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=4000)),
                ('rules', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Events.models.upload_image_path)),
            ],
        ),
    ]
