# Generated by Django 2.0.2 on 2018-02-20 11:56

import Events.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('team_head_name', models.CharField(max_length=100)),
                ('team_head_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=4000)),
                ('rules', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Events.models.upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Category')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.SubCategory'),
        ),
    ]
