# Generated by Django 2.0.2 on 2018-02-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='department',
            field=models.CharField(default='Computer Science and Engineering', max_length=100),
        ),
    ]
