# Generated by Django 2.0.2 on 2018-02-13 21:13

import Events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Events.models.upload_image_path),
        ),
    ]
