# Generated by Django 2.0.2 on 2018-02-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_subcategory_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='team_head_mobile',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='team_head_name',
            field=models.TextField(max_length=1000),
        ),
    ]
