# Generated by Django 2.0.2 on 2018-02-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_category_back_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
