# Generated by Django 2.0.2 on 2018-03-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='event',
            name='summary',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
