# Generated by Django 2.0.2 on 2018-03-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_auto_20180302_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_event',
            field=models.BooleanField(default=False),
        ),
    ]
