# Generated by Django 2.0.2 on 2018-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_remove_event_team_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_event',
            field=models.BooleanField(default=False),
        ),
    ]
