# Generated by Django 2.0.2 on 2018-03-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_remove_event_team_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group_event',
            field=models.BooleanField(default=False),
        ),
    ]
