# Generated by Django 2.0.2 on 2018-03-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_auto_20180308_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
