# Generated by Django 2.0.2 on 2018-03-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0014_auto_20180308_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reg_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
