# Generated by Django 2.0.2 on 2018-02-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Rohan Malik', max_length=255),
            preserve_default=False,
        ),
    ]
