# Generated by Django 2.0.2 on 2018-02-18 06:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20180218_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
