# Generated by Django 2.0.2 on 2018-02-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
