# Generated by Django 2.0.2 on 2018-03-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20180302_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
    ]
