# Generated by Django 2.0.2 on 2018-03-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='fees_paid',
            field=models.BooleanField(default=False),
        ),
    ]
