# Generated by Django 2.0.2 on 2018-03-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Participation', '0002_participate_fees_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participate',
            name='fees_paid',
        ),
    ]
